[32mINFO    [0m LoginPage:base_page.py:30 Entered 'fyctest5401+7@gmail.com' into element: ('id', 'email')
[32mINFO    [0m LoginPage:base_page.py:30 Entered 'betatp6tp6' into element: ('id', 'password')
[32mINFO    [0m LoginPage:login_page.py:10 Entered credentials for email: fyctest5401+7@gmail.com
[32mINFO    [0m LoginPage:base_page.py:20 Clicked element: ('xpath', "//button[@type='submit' and text()='Continue']")
[32mINFO    [0m LoginPage:login_page.py:28 Clicked on TP login button
[32mINFO    [0m TPDashboardPage:base_page.py:55 
Modal was not present
[32mINFO    [0m TPDashboardPage:base_page.py:20 Clicked element: ('xpath', "//button[.//span[text()='Courses']]")
[32mINFO    [0m LoginPage:base_page.py:30 Entered 'composition-swing@gnjvogqr.mailosaur.net' into element: ('id', 'email')
[32mINFO    [0m LoginPage:base_page.py:30 Entered 'l4l4l4l4' into element: ('id', 'password')
[32mINFO    [0m LoginPage:login_page.py:10 Entered credentials for email: composition-swing@gnjvogqr.mailosaur.net
[32mINFO    [0m LoginPage:base_page.py:20 Clicked element: ('xpath', "//button[@type='submit']")
[32mINFO    [0m LoginPage:login_page.py:19 Clicked on continue button
[32mINFO    [0m EnquiryModal:base_page.py:20 Clicked element: ('xpath', "//button[text()='Learn More']")
[32mINFO    [0m EnquiryModal:base_page.py:20 Clicked element: ('xpath', "//button[text()='Send Enquiry']")
[32mINFO    [0m TPEnquiriesPage:base_page.py:20 Clicked element: ('xpath', "//button[.//span[text()='Learners']]")
[32mINFO    [0m TPEnquiriesPage:base_page.py:20 Clicked element: ('xpath', "//button[contains(.,'Enquiries')]")
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016627FCAF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/00d6f18e2ac137e85fe346e893549ec4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016627FC9370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/00d6f18e2ac137e85fe346e893549ec4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000166280048F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/00d6f18e2ac137e85fe346e893549ec4